GPUS: '0'
DATA_DIR: ''
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  DATASET: "custom_mpii"
#  ROOT: '/home/dm/data3/dataset/face_person/MPII/'
  ROOT: '/data3/panjinquan/dataset/face_person/MPII/'
#  ROOT: '/data/panjinquan/mpii/'
  TEST_SET: valid
  TRAIN_SET: train
  FLIP: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
MODEL:
  NAME: 'mobilenet_v2'
  PRETRAINED: './pretrained/pytorch/imagenet/mobilenet_v2-b0353104.pth'
  IMAGE_SIZE:
  - 192
  - 256
  NUM_JOINTS: 6
  EXTRA:
    TARGET_TYPE: gaussian
    SIGMA: 2
    HEATMAP_SIZE:
    - 48
    - 64
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 16
    - 16
    - 16
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    WIDTH_MULT: 1.0
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 64
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: false
  OPTIMIZER: adam
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP: [90,120,150]
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 64
  FLIP_TEST: true
  MODEL_FILE: ''
DEBUG:
  DEBUG: false
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
