GPUS: '5'
DATA_DIR: ''
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  DATASET: 'custom_coco'
  ROOT: '/home/dm/data3/dataset/finger_keypoint/finger1/'
  TEST_SET: 'val'
  TEST_FILE: 'val_finger_pen_coco.json'
  TRAIN_SET: 'train'
  TRAIN_FILE: 'train_finger_pen_coco.json'
  FLIP: true
  ROT_FACTOR: 40
  SCALE_FACTOR: 0.3
MODEL:
  NAME: 'pose_hrnet'
  PRETRAINED: 'data/pretrained/imagenet/hrnet_w48-8ef0771d.pth'
#  PRETRAINED: ''
  IMAGE_SIZE:
  - 256
  - 256
  NUM_JOINTS: 4
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 64
    - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    NUM_LAYERS: 48
    PRETRAINED_LAYERS:
      - 'conv1'
      - 'bn1'
      - 'conv2'
      - 'bn2'
      - 'layer1'
      - 'transition1'
      - 'stage2'
      - 'transition2'
      - 'stage3'
      - 'transition3'
      - 'stage4'
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 16
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: false
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 16
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  BBOX_THRE: 1.0
  FLIP_TEST: false
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
