GPUS: '7'
DATA_DIR: ''
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 1
PRINT_FREQ: 10

DATASET:
  DATASET: 'custom_coco'
  ROOT: '/home/dm/data3/dataset/finger_keypoint/finger/'
#  ROOT: '/data3/data3/dataset/finger_keypoint/finger/'
  TEST_SET: 'val'
  TEST_FILE: 'annotations/val_finger_pen_coco.json'
  TRAIN_SET: 'val'
#  TRAIN_FILE: 'val_finger_pen_coco.json'
  TRAIN_FILE: 'annotations/val_finger_pen_coco.json'
  FLIP: true
  ROT_FACTOR: 40
  SCALE_FACTOR: 0.3
MODEL:
  NAME: 'model_mobilenet_v2'
  PRETRAINED: './data/pretrained/pytorch/imagenet/resnet18-5c106cde.pth'
  IMAGE_SIZE:
  - 288
  - 192
  NUM_JOINTS: 4
  EXTRA:
#    TARGET_TYPE: 'offset'
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 72
    - 48
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 16
    - 16
    - 16
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 18
    WIDTH_MULT: 0.5
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 32
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: false
  OPTIMIZER: 'adam'
  LR: 0.01
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120 
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 32
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  BBOX_THRE: 1.0
  FLIP_TEST: false
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
